// lib/email/templates.ts
import { getTranslations } from 'next-intl/server';

// ============================================================
// 类型定义
// ============================================================

export interface LoginEmailParams {
  code: string;
  siteName: string;
  locale?: string; // 默认 'en'
}

export interface SubscriptionEmailParams {
  siteName: string;
  unsubscribeUrl: string;
  locale?: string; // 默认 'en'
}

export interface OrderEmailParams {
  orderId: string;
  amount: string;
  dueDate?: string;
  shareUrl: string;
  pdfUrl?: string;
  siteName: string;
  locale?: string; // 默认 'en'
}

// ============================================================
// 工具：获取翻译（带默认 locale）
// ============================================================

async function getEmailTranslations(namespace: string, locale: string = 'en') {
  return getTranslations({ locale, namespace });
}

// ============================================================
// 1. 登录验证码邮件模板
// ============================================================

export async function generateLoginEmailSubject(params: LoginEmailParams): Promise<string> {
  const { code, siteName, locale = 'en' } = params;
  const t = await getEmailTranslations('email.login', locale);
  return `${siteName} - ${t('subject')}`;
}

export async function generateLoginEmailHtml(params: LoginEmailParams): Promise<string> {
  const { code, siteName, locale = 'en' } = params;
  const t = await getEmailTranslations('email.login', locale);

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 560px; margin: 0 auto; padding: 32px 24px; border: 1px solid #e8e8e8; border-radius: 12px; background: #ffffff;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a1a; font-size: 24px; margin: 0;">${siteName}</h1>
        <p style="color: #888; font-size: 14px; margin: 4px 0 0;">${t('title')}</p>
      </div>
      <div style="background: #f7f9fc; border-radius: 8px; padding: 24px; text-align: center; margin: 20px 0;">
        <p style="color: #666; font-size: 14px; margin: 0 0 12px;">${t('enterCode')}</p>
        <div style="background: #ffffff; padding: 16px; border-radius: 6px; font-size: 40px; letter-spacing: 12px; font-weight: 700; color: #1a1a1a; border: 1px dashed #d0d5dd;">
          ${code}
        </div>
      </div>
      <div style="color: #888; font-size: 13px; line-height: 1.6;">
        <p style="margin: 0 0 4px;">${t('validity')}</p>
        <p style="margin: 0;">${t('doNotShare')}</p>
      </div>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0 16px;">
      <div style="color: #aaa; font-size: 12px; text-align: center;">
        <p style="margin: 0;">${t('autoGenerated')}</p>
        <p style="margin: 4px 0 0;">${t('ignoreIfNotRequested')}</p>
      </div>
    </div>
  `;
}

// ============================================================
// 2. 订阅确认邮件模板
// ============================================================

export async function generateSubscriptionEmailSubject(params: SubscriptionEmailParams): Promise<string> {
  const { siteName, locale = 'en' } = params;
  const t = await getEmailTranslations('email.subscription', locale);
  return t('confirmSubject', { siteName });
}

export async function generateSubscriptionEmailHtml(params: SubscriptionEmailParams): Promise<string> {
  const { siteName, unsubscribeUrl, locale = 'en' } = params;
  const t = await getEmailTranslations('email.subscription', locale);

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 560px; margin: 0 auto; padding: 32px 24px; border: 1px solid #e8e8e8; border-radius: 12px; background: #ffffff;">
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="font-size: 48px; margin-bottom: 8px;">📬</div>
        <h1 style="color: #1a1a1a; font-size: 22px; margin: 0;">${t('thankYou')}</h1>
        <p style="color: #666; font-size: 14px; margin: 4px 0 0;">${t('confirmSuccess', { siteName })}</p>
      </div>

      <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <p style="color: #166534; font-size: 14px; margin: 0; text-align: center;">✅ ${t('confirmBadge')}</p>
      </div>

      <div style="color: #555; font-size: 14px; line-height: 1.8;">
        <p style="margin: 0;">${t('greeting')}</p>
        <p style="margin: 8px 0;">${t('welcome')}</p>
        <ul style="margin: 8px 0; padding-left: 20px; color: #555;">
          <li>📰 ${t('benefit1')}</li>
          <li>💡 ${t('benefit2')}</li>
          <li>🎁 ${t('benefit3')}</li>
        </ul>
        <p style="margin: 12px 0 0; color: #888; font-size: 13px;">💡 ${t('unsubscribeHint')}</p>
      </div>

      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0 16px;">

      <div style="color: #aaa; font-size: 12px; text-align: center;">
        <p style="margin: 0;">${t('autoGenerated')}</p>
        <p style="margin: 4px 0 0;">
          <a href="${unsubscribeUrl}" style="color: #aaa; text-decoration: underline;">
            ${t('unsubscribeLink')}
          </a>
        </p>
      </div>
    </div>
  `;
}

// ============================================================
// 3. 订单邮件模板
// ============================================================

export async function generateOrderEmailSubject(params: OrderEmailParams): Promise<string> {
  const { orderId, siteName, locale = 'en' } = params;
  const t = await getEmailTranslations('email.order', locale);
  return t('subject', { orderId, siteName });
}

export async function generateOrderEmailHtml(params: OrderEmailParams): Promise<string> {
  const { orderId, amount, dueDate, shareUrl, pdfUrl, siteName, locale = 'en' } = params;
  const t = await getEmailTranslations('email.order', locale);

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 560px; margin: 0 auto; padding: 32px 24px; border: 1px solid #e8e8e8; border-radius: 12px; background: #ffffff;">
      <div style="text-align: center; margin-bottom: 24px;">
        <div style="font-size: 42px; margin-bottom: 8px;">📄</div>
        <h1 style="color: #1a1a1a; font-size: 22px; margin: 0;">${t('title')}</h1>
        <p style="color: #666; font-size: 14px; margin: 4px 0 0;">${siteName}</p>
      </div>

      <div style="background: #f7f9fc; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
          <tr>
            <td style="color: #666; padding: 6px 0;">📋 ${t('orderId')}</td>
            <td style="color: #1a1a1a; font-weight: 600; padding: 6px 0; text-align: right;">${orderId}</td>
          </tr>
          <tr>
            <td style="color: #666; padding: 6px 0;">💰 ${t('amount')}</td>
            <td style="color: #1a1a1a; font-weight: 600; padding: 6px 0; text-align: right;">${amount}</td>
          </tr>
          ${dueDate ? `
          <tr>
            <td style="color: #666; padding: 6px 0;">📅 ${t('dueDate')}</td>
            <td style="color: #1a1a1a; padding: 6px 0; text-align: right;">${dueDate}</td>
          </tr>
          ` : ''}
        </table>
      </div>

      <div style="text-align: center; margin: 24px 0;">
        <a href="${shareUrl}" style="display: inline-block; background: #1a1a1a; color: #ffffff; padding: 12px 40px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px;">
          ${t('viewButton')}
        </a>
      </div>

      ${pdfUrl ? `
      <div style="text-align: center; margin: 12px 0 24px;">
        <a href="${pdfUrl}" style="color: #0070f3; text-decoration: underline; font-size: 13px;">
          📎 ${t('downloadPdf')}
        </a>
      </div>
      ` : ''}

      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0 16px;">
      <div style="color: #aaa; font-size: 12px; text-align: center;">
        <p style="margin: 0;">${t('autoGenerated')}</p>
      </div>
    </div>
  `;
}